Fixes the practically undefined behaviour with abs(INT_MIN), here implemented with the macro "UNSIGNED_VALUE_OF( x ) ( x < 0 ? -x : x )", which breaks the unit test "CHECK_EQUAL( "-2147483648", FIX::IntConvertor::convert( MIN_INT ) );" when compiled with gcc-4.9 -O2.
<ut>
  <output>
C++/test/FieldConvertorsTestCase.cpp:114: error: Failure in integerConvertTo: Expected -2147483648 but was -00
FAILURE: 1 out of 186 tests failed (1 failures).
Test time: 10.79 seconds.
  </output>
</ut>

2147483648 doesn't fit in an int (max is 2147483647). Casting to long long (so it works on 32-bit too) before negating it solves the corner case problem.